# Generated by Django 3.2.13 on 2022-06-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortener',
            options={'ordering': ['-created']},
        ),
    ]
